-- =========================================================
-- EXPAND ALL COMMUNITY UPDATES — full detail for every row
-- Run once in Supabase SQL Editor.
-- Safe to re-run: ON CONFLICT DO UPDATE refreshes body + detail.
-- Generated by: node scripts/expand-changelog-details.mjs
-- =========================================================

INSERT INTO public.app_updates (
  id, date, title, body, detail, "directorName", "directorTitle", "postedByUserId"
) VALUES
(
  '2026-06-09_real-notifications-not-just-test',
  '2026-06-09',
  'Real alerts work again — not just test push',
  'Messages, listings, comments, and other alerts deliver again. Only the test button had been working for many neighbors.',
  $detail$WHAT NEIGHBORS SEE
After this deploy, alerts for real activity (new messages, listing changes, comments, votes, support replies, etc.) should reach your device again — not only the “Send test notification” button in Account → Push notifications.

WHAT WAS BROKEN
We had turned off client-side push dispatch to stop duplicate notifications. That left many alert types dependent on Supabase database webhooks alone. If webhooks were missing or a preference row had enabled=false stuck in the database, every real push was filtered out — while the test endpoint (/api/push/test) still worked because it bypasses preference checks and webhooks.

WHAT WE CHANGED (CODE)

1) Re-enabled client dispatch — src/lib/pushConfig.ts
   export const CLIENT_PUSH_DISPATCH_ENABLED = true;
   The app again calls push helpers after Supabase writes (src/supabase.ts → runPushTask). Server webhooks remain the backup when the app is closed.

2) Dedup prevents doubles — api/push/_server/pushDedup.ts
   claimPushDispatch(tag) writes to push_dispatch_log with a 90-second window. Client and webhook both may fire; only the first send with a given tag goes through.

3) Subscribe fixes stuck “all off” prefs — api/push/_server/pushSubscribe.ts
   New ensureNotificationPreferencesOnSubscribe(userId): if a notification_preferences row already exists, we UPDATE enabled=true without wiping other toggles. Previously ignoreDuplicates on subscribe left enabled=false forever, blocking all real pushes.

4) Same subscribe fix on the client — src/lib/pushNotifications.ts
   savePushSubscriptionDirect() now calls ensureNotificationPreferencesOnSubscribe() instead of upsert with ignoreDuplicates.

5) Aligned dedup tags — src/lib/pushEvents.ts + api/push/_server/neighborNotify.ts
   Messages use msg-{messageId}, pickup chat notes use pickup-msg-{messageId}, announcements use announcement-{id} so client and server share tags.

FILES TOUCHED
src/lib/pushConfig.ts, src/supabase.ts, src/lib/pushIntegration.ts, src/lib/pushEvents.ts, api/push/_server/pushSubscribe.ts, api/push/subscribe.ts, server/app.ts

WHAT YOU SHOULD DO
On each device: Help or Account → Push notifications → turn off, then on again once. Tap Save settings if you changed toggles. Confirm test push still works, then trigger a real event (have someone message you).$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_stable-after-sign-in',
  '2026-06-09',
  'App stays open after you sign in',
  'Fixed white screens and “Something went wrong” crashes right after login when opening notification settings.',
  $detail$WHAT NEIGHBORS SEE
Signing in should land you on the feed without a blank page or error boundary. Opening Help → notification-related panels should no longer crash the whole app.

ROOT CAUSES

1) Duplicate Supabase Realtime channels
   Two components both called usePushNotifications(userId) with the same channel name live-notification-prefs-{userId}. Supabase throws: “cannot add postgres_changes callbacks after subscribe()”. That uncaught error took down the React tree.

2) Logout race with push cleanup
   clearNotificationDataOnLogout() ran during sign-out while hooks still mounted, causing state updates on unmounted components.

WHAT WE CHANGED (CODE)

1) Unique realtime channel per hook instance — src/hooks/usePushNotifications.ts
   realtimeChannelIdRef uses crypto.randomUUID() so channelName becomes live-notification-prefs-{userId}-{uuid}.

2) Lightweight celebration modal — src/components/PushNotificationCelebration.tsx
   usePushNotifications(userId, { syncPreferences: false }) so the onboarding prompt does not open a second prefs channel.

3) Hook order + guards — src/App.tsx
   useRef/useState order fixed; logout paths guard against races while notification session clears.

4) Error boundary — src/components/AppErrorBoundary.tsx
   Catches render crashes with a recoverable message instead of a white screen.

5) Missing import — src/components/Onboarding.tsx
   Added Heart icon import that had been causing a secondary crash.

FILES TOUCHED
src/hooks/usePushNotifications.ts, src/components/PushNotificationCelebration.tsx, src/components/NotificationSettings.tsx, src/App.tsx, src/components/AppErrorBoundary.tsx, src/lib/pushNotifications.ts (clearNotificationDataOnLogout)

VERIFICATION
Sign in on phone and desktop, open Help, expand notification settings, switch accounts — app should remain interactive.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_staff-announcements-in-help',
  '2026-06-09',
  'Staff announcements in Help',
  'Help now has a separate Announcements board: staff post news, neighbors vote and comment on each post.',
  $detail$WHAT NEIGHBORS SEE
Help & support → Announcements. Tap a post to expand it, upvote/downvote, and join the discussion in comments. This is separate from App updates (director changelog).

WHAT STAFF SEE
Any staff role can tap Post announcement. Authors and the director can edit or delete their posts. Votes help staff see what resonates.

DATABASE (run in Supabase SQL Editor)
1) supabase-sql/help-announcements.sql — table help_announcements
2) supabase-sql/help-announcement-comments.sql — table help_announcement_comments
3) supabase-sql/add-app-updates-notification-pref.sql — appUpdates column + announcement vote type

TABLE: help_announcements
Columns mirror app_updates but use authorName/authorTitle instead of directorName. postedByUserId links to users.uid.

TABLE: help_announcement_comments
announcementId → help_announcements.id ON DELETE CASCADE, plus denormalized userName, userNeighborhood, text.

VOTES
community_content_votes.targetType now includes 'announcement' (see community-content-votes.sql). AnnouncementsList uses useCommunityContentVotes('announcement', ids).

COMMENTS
src/hooks/useHelpAnnouncementComments.ts — loads comments, realtime on help_announcement_comments, optimistic add/delete.
src/components/AnnouncementComments.tsx — discussion UI under expanded posts.

CRUD / API LAYER — src/supabase.ts
getSupabaseHelpAnnouncements, createSupabaseHelpAnnouncement, updateSupabaseHelpAnnouncement, deleteSupabaseHelpAnnouncement, comment helpers.

PERMISSIONS — src/lib/roles.ts
canPostAnnouncements() = any staff role.
canEditAnnouncement(actor, postedByUserId) = author or director.

UI
src/components/AnnouncementsList.tsx — main list (forked from UpdatesList with comments).
src/components/AccountHelpSection.tsx — second Help tile for Announcements vs App updates.

PUSH
help_announcements INSERT → api/push/_server/webhookDispatch.ts → runAnnouncementNotify → eventType 'announcement' → notifications toggle announcements.

Add 15th webhook: help_announcements INSERT → /api/webhooks/supabase-push$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_app-updates-vs-announcements-notifications',
  '2026-06-09',
  'App updates and announcements are separate in notifications',
  'Notification settings now have distinct toggles: App updates (director changelog) vs Announcements (staff Help posts).',
  $detail$WHY WE SPLIT THEM
App updates = director changelog in app_updates (technical “what shipped”). Announcements = staff community news in help_announcements (Help board with votes/comments). They must not share one push preference.

NOTIFICATION TOGGLES — src/components/NotificationSettings.tsx
Community section now has:
• App updates → preference key appUpdates
• Announcements → preference key announcements
• Account updates → accountUpdates (suspensions, bans, role changes — unchanged)

DATABASE
ALTER TABLE notification_preferences ADD COLUMN IF NOT EXISTS "appUpdates" BOOLEAN DEFAULT true;
(see supabase-sql/add-app-updates-notification-pref.sql)

SERVER PREF MAP — api/push/_server/pushDelivery.ts
EVENT_PREF_MAP:
  app_update → appUpdates
  announcement → announcements
  account_update → accountUpdates

PUSH EVENT TYPES — api/push/_server/pushDelivery.ts PushEventType
Added app_update alongside announcement.

WEBHOOK ROUTING — api/push/_server/webhookDispatch.ts
• app_updates INSERT → runAppUpdateNotify (api/push/_server/appUpdateNotify.ts) → url /updates
• help_announcements INSERT → runAnnouncementNotify → url /help/announcements

CLIENT PUSH — src/lib/pushEvents.ts
notifyAppUpdate() sends eventType app_update.
notifyCommunityAnnouncement() sends eventType announcement.

DEEP LINKS — src/lib/pushDeepLink.ts
/updates opens Help → App updates panel.
/help/announcements opens Help → Announcements panel.
App.tsx passes initialHelpPanel through MobileView / TabletView / DesktopView → CommunityMenuView → AccountHelpSection.

WEBHOOK DOC — supabase-sql/supabase-push-webhook.sql
Row 14: push-app-updates on app_updates INSERT.
Row 15: push-announcements on help_announcements INSERT (not app_updates).$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_logout-clears-device-push',
  '2026-06-09',
  'Logout clears notification data on this device',
  'Signing out removes this phone’s push subscription and in-memory notification UI so the next account does not inherit your alerts.',
  $detail$WHAT NEIGHBORS SEE
After logout, notification toggles reset in the UI until the next account loads its saved preferences from the database. The device is no longer registered to receive pushes for the signed-out account.

WHAT STAYS IN THE DATABASE
Per-account notification_preferences remain saved (toggles you tapped Save settings for). Only device push subscription rows and local session state are cleared.

CODE PATH — src/lib/pushNotifications.ts
clearNotificationDataOnLogout(userId):
1) detachPushSubscriptionForUser(uid) — removes push_subscriptions row for this endpoint and calls subscription.unsubscribe() in the browser.
2) Clears celebration localStorage key sbn_push_celebration_prompt_dismissed_v1.
3) Broadcasts NOTIFICATION_SESSION_CLEARED_EVENT so usePushNotifications resets to CLEARED_NOTIFICATION_PREFERENCES in memory.

HOOK — src/hooks/usePushNotifications.ts
Listens for sbn-notification-session-cleared and calls resetPreferencesState().

CALLED FROM — src/App.tsx handleLogOut
await clearNotificationDataOnLogout(userProfile.uid) before supabase.auth.signOut().

IMPORTANT
Prefs are per account in notification_preferences (one row per userId). Push delivery is per device in push_subscriptions. Re-enable notifications after switching accounts.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_notification-settings-save-button',
  '2026-06-09',
  'Save button for notification toggles',
  'Notification preferences now load from your account in the database and save only when you tap Save settings.',
  $detail$SUMMARY FOR NEIGHBORS
Your notification choices are stored per account in Supabase, not silently in the browser. Flip toggles, review them, then tap Save settings. Discard reverts to last saved state.

UI — src/components/NotificationSettings.tsx
• hasUnsavedChanges banner with Save settings + Discard buttons.
• setDraftPreferences() updates local React state only until save.
• savePreferences() → saveNotificationPreferences() in src/lib/pushNotifications.ts → upsert notification_preferences.

HOOK — src/hooks/usePushNotifications.ts
preferences vs savedPreferences state, preferencesEqual(), hasUnsavedRef prevents realtime reload from overwriting unsaved edits.

DATABASE
Table notification_preferences (see supabase-sql/notifications-complete.sql). Realtime channel syncs across tabs when another device saves.

LOGOUT BEHAVIOR
clearNotificationDataOnLogout clears device push + in-memory UI; DB prefs for the account remain for next login.

WHY NOT AUTOSAVE
Prevents accidental toggles and matches “prefs per account, push per device” model documented in Help copy.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_every-alert-like-new-listings',
  '2026-06-09',
  'Every alert works like new listings',
  'Messages, comments, votes, pickup reminders, account notices, and community announcements now deliver the same reliable way as new listing alerts.',
  $detail$ARCHITECTURE
New listings were the reference path: Supabase INSERT on items → webhook → api/webhooks/supabase-push → api/push/_server/webhookDispatch.ts → neighborNotify → runPushSend → sendPushToUsers.

WEBHOOK HANDLERS ADDED/COMPLETED — webhookDispatch.ts
• message_requests INSERT/UPDATE (accepted)
• item_claim_requests, item_claims, item_comments, item_votes
• messages INSERT (per-message tags msg-{messageId})
• items UPDATE → status, pickup_scheduled, saved-item alerts
• moderation_audit_log → account_update pushes
• app_updates / help_announcements → changelog vs staff announcements
• support_ticket_messages, user_reports, app_updates

DEDUP — api/push/_server/pushDedup.ts
push_dispatch_log table with UNIQUE(tag). Fail-open on DB errors except duplicate 23505.

CLIENT DISPATCH — src/lib/pushConfig.ts
CLIENT_PUSH_DISPATCH_ENABLED true again with dedup tags matching server.

SQL SETUP
supabase-sql/notifications-complete.sql, supabase-sql/supabase-push-webhook.sql (15 webhooks), push_dispatch_log unique index on tag.

CRON — api/cron/notification-jobs.ts
Listing expiry + pickup reminders when app closed.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_no-more-double-pings',
  '2026-06-09',
  'No more double pings',
  'Stopped the same alert from firing twice when both the app and the server tried to send it.',
  $detail$PROBLEM
Client runPushTask() in src/supabase.ts and Supabase webhooks both fired on the same database event → two notifications.

PHASE 1 FIX
Set CLIENT_PUSH_DISPATCH_ENABLED = false in src/lib/pushConfig.ts — stopped doubles but broke alerts when webhooks absent.

PHASE 2 FIX (current)
Re-enabled client dispatch WITH dedup:
• api/push/_server/pushDedup.ts — claimPushDispatch(tag)
• Matching tags in src/lib/pushEvents.ts and api/push/_server/neighborNotify.ts
• Bad tags fixed: msg-{chatId} → msg-{messageId}, static community-announcement → announcement-{id}

SERVICE WORKER — public/service-worker.js
Removed unauthenticated resubscribe that reassigned endpoints to wrong users.

SUBSCRIBE — api/push/_server/pushSubscribe.ts claimPushSubscriptionForUser deletes endpoint then upserts for signed-in userId.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_notifications-right-account',
  '2026-06-09',
  'Notifications go to the right account',
  'Fixed push sometimes landing on the wrong neighbor on shared phones — your alerts stay tied to whoever is signed in.',
  $detail$PROBLEM
Shared devices: browser push endpoint stayed registered to previous user’s row in push_subscriptions.

FIX — api/push/_server/pushSubscribe.ts claimPushSubscriptionForUser()
1) DELETE FROM push_subscriptions WHERE endpoint = $endpoint
2) UPSERT row with current auth userId, p256dh, auth keys

CLIENT — src/lib/pushNotifications.ts persistPushSubscription() posts to /api/push/subscribe with Bearer token.

RESUBSCRIBE — api/push/resubscribe.ts requires auth (removed service worker silent resubscribe).

LOGOUT — clearNotificationDataOnLogout() detaches subscription for signed-out user.

AFTER DEPLOY
Each neighbor: notifications off → on once while signed in as themselves.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_comment-and-saved-listing-alerts',
  '2026-06-09',
  'Comment & saved-listing alerts',
  'Get notified when someone comments on your listing — or when a bookmarked post is edited, commented on, or changes status.',
  $detail$WHAT NEIGHBORS SEE
Listing owners get a push when someone comments on their post. Neighbors who bookmark a listing get alerts when that post is edited, commented on, claimed, or changes status (active → pending pickup → completed).

NOTIFICATION TOGGLES — src/components/NotificationSettings.tsx
• Your listings → Comments
• Saved items → edits, comments, claims, status changes

SERVER — api/push/_server/neighborNotify.ts + webhookDispatch.ts
item_comments INSERT → comment push to owner + saved-item bookmarkers.
items UPDATE → listingStatus / saved-item paths with dedup tags.

CLIENT — src/hooks/useSavedItemPushAlerts.ts watches saved listing IDs for changes when app is open.

DATA — saved_items table (synced from local bookmarks via migrateLocalSavedItemsToDb in src/supabase.ts).

SETUP
Each comment is its own alert (not bundled). Toggle Saved items if you only want alerts on bookmarked posts.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_listing-vote-alerts',
  '2026-06-09',
  'Upvote & downvote alerts',
  'Optional push when neighbors upvote or downvote your listings — each with its own toggle.',
  $detail$WHAT NEIGHBORS SEE
Optional push when neighbors upvote or downvote your listings — each direction has its own toggle.

TOGGLES — Account → Push notifications → Your listings → Upvotes / Downvotes

SERVER — item_votes INSERT/UPDATE webhook → api/push/_server/neighborNotify.ts
Respects listingUpvotes and listingDownvotes preference keys.

UI — src/components/ListingEngagement.tsx records votes; ItemDetailView shows counts.

WORKS IN BACKGROUND when push is enabled and device subscription is valid (Add to Home Screen on iPhone).$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_saved-bookmarks-sync-online',
  '2026-06-09',
  'Saved bookmarks sync online',
  'When you save a listing, the bookmark is stored in the community database so alerts still reach you when the app is closed.',
  $detail$WHAT NEIGHBORS SEE
Saving a listing now stores the bookmark in your account online — not only on this phone — so the server can alert you when that post changes.

BEFORE
localStorage key sbn_saved_items_v1 only — server could not notify when app was closed.

AFTER — src/hooks/useSavedItems.ts + src/supabase.ts
syncSavedItemBookmark(userId, itemId, saved) writes saved_items rows.
migrateLocalSavedItemsToDb() on login imports old local bookmarks.

PUSH — src/hooks/useSavedItemPushAlerts.ts + webhooks on items/item_comments/item_claims.

UI — bookmark button on ItemCard.tsx and ItemDetailView.tsx; “Saved” quick pick in ItemGrid.tsx.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_fewer-duplicate-notifications',
  '2026-06-09',
  'Fewer duplicate notifications',
  'Fixed double alerts when the same event fired from the app and the server at the same time.',
  $detail$WHAT NEIGHBORS SEE
The same event should not ping your phone twice when both the open app and the server tried to send at once.

FIX — api/push/_server/pushDedup.ts
claimPushDispatch(tag) inserts into push_dispatch_log with UNIQUE(tag) and ~90s window.

TAGS — src/lib/pushEvents.ts aligns client tags with api/push/_server/neighborNotify.ts (msg-{messageId}, etc.).

SUBSCRIBE HARDENING — api/push/_server/pushSubscribe.ts + api/push/resubscribe.ts keep endpoint rows valid after deploys.

SQL
CREATE UNIQUE INDEX IF NOT EXISTS push_dispatch_log_tag_unique ON push_dispatch_log (tag);$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_director-oversight-alerts',
  '2026-06-09',
  'Director oversight alerts',
  'Directors get optional push for all eight oversight categories — joins, departures, moderation, reports, tickets, listings, message requests, and claim requests.',
  $detail$WHAT NEIGHBORS SEE (DIRECTORS)
Eight optional oversight categories in push settings: joins, departures, moderation, reports, tickets, listings, message requests, claim requests.

UI — src/components/NotificationSettings.tsx → Director oversight section

SERVER — api/push/_server/directorNotify.ts + webhookDispatch.ts
users INSERT/DELETE, moderation_audit_log, user_reports, support_tickets, items, message_requests, item_claim_requests.

DEEP LINK — /director/overview → DirectorSiteOverview.tsx

Each category has its own toggle — turn off noise you do not need.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_push-alerts-in-the-background',
  '2026-06-09',
  'Push alerts in the background',
  'Notifications now reach your phone when the app is closed — not only while Sacramento Buy Nothing is open.',
  $detail$WHAT NEIGHBORS SEE
Notifications reach your phone when Sacramento Buy Nothing is closed — not only while the tab is open.

STACK
• public/service-worker.js — push event + notificationclick → deep link
• Supabase webhooks → api/webhooks/supabase-push → runPushSend
• VAPID keys in Vercel env (VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY)

IPHONE
Safari tabs alone do not get background push. Add to Home Screen (iOS 16.4+). InstallPrompt.tsx explains steps.

CLIENT — src/lib/pushNotifications.ts subscribe flow + src/pwa/registerServiceWorker.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_all-notification-toggles',
  '2026-06-09',
  'All notification toggles work',
  'Every switch in push settings now delivers reliably — messages, claims, discover, staff inbox, pickup reminders, listing status, and more.',
  $detail$WHAT NEIGHBORS SEE
Every switch in Account → Push notifications should deliver when enabled — messages, claims, discover, staff inbox, pickup reminders, listing status, support, announcements, and more.

PREFS TABLE — notification_preferences (supabase-sql/notifications-complete.sql)

SERVER MAP — api/push/_server/pushDelivery.ts EVENT_PREF_MAP filters each eventType

WEBHOOKS — supabase-sql/supabase-push-webhook.sql (15 handlers documented)

CRON — api/cron/notification-jobs.ts for listing expiry + pickup reminders

AFTER DEPLOY
Run notifications SQL, confirm webhooks, toggle notifications off → on once per device.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_feed-renamed-to-stuff',
  '2026-06-09',
  'Feed renamed to Stuff',
  'The community listings tab is now called Stuff — same free gifts and requests, friendlier name.',
  $detail$WHAT NEIGHBORS SEE
The main listings tab label changed from “Feed” to “Stuff” — same free gifts and ISO requests, friendlier name.

COPY — src/siteContent.ts
IN_APP.feedTabLabel = 'Stuff'
IN_APP.feedTitle = 'Community Stuff'

NAV — src/components/MobileView.tsx, TabletView.tsx, Navbar.tsx use IN_APP.feedTabLabel

No database changes — display copy only.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_updates-live-in-the-database',
  '2026-06-09',
  'Updates live in the database',
  'The director can post, edit, and delete changelog entries from Help & support. Neighbors see who posted each update.',
  $detail$WHAT NEIGHBORS SEE
Director changelog entries live in Supabase, not hard-coded. Neighbors read them under Community hub → App updates; director can post, edit, delete.

TABLE — app_updates (supabase-sql/app-updates.sql)
Columns: id, date, title, body, detail, directorName, postedByUserId

UI — src/components/UpdatesList.tsx, AppUpdateEditModal.tsx
API — src/supabase.ts getSupabaseAppUpdates, create/update/delete

PUBLIC — src/components/public/pages/UpdatesPage.tsx (#/updates)

VOTES — community_content_votes targetType 'update'$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_test-push-notifications',
  '2026-06-09',
  'Test push notifications',
  'Send yourself a test alert from Account → Push notifications after you subscribe on a device.',
  $detail$WHAT NEIGHBORS SEE
After enabling push, tap “Send test notification” in Account → Push notifications to confirm this device receives alerts.

ENDPOINT — api/push/test.ts (bypasses preference checks — always sends to your subscription)

CLIENT — src/lib/pushNotifications.ts sendTestPush()

USE THIS to verify VAPID keys and service worker before debugging “real” alerts that depend on prefs + webhooks.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_each-staff-member-writes-their-own-message',
  '2026-06-09',
  'Each staff member writes their own message',
  'Team notes are personal now — every staff member publishes their own welcome message on home and reviews.',
  $detail$WHAT NEIGHBORS SEE
Each staff member publishes their own welcome note on home and reviews — not one shared city-manager message.

TABLE — staff_messages (supabase-sql/staff-messages.sql)
PK userId — one row per staff member

UI — src/components/StaffMessage.tsx, PublishedStaffMessages.tsx, LeadershipMessagesCarousel.tsx
HOOKS — useStaffMessage.ts, usePublishedStaffMessages.ts

PERMS — canEditOwnStaffMessage() in src/lib/roles.ts
Director note remains separate in director_message table.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_vote-on-updates-reviews-team-notes',
  '2026-06-09',
  'Vote on updates, reviews & team notes',
  'Upvote or downvote changelog entries, neighbor reviews, and staff messages. Update votes go to your director.',
  $detail$WHAT NEIGHBORS SEE
Upvote or downvote changelog entries, neighbor app reviews, and staff/director welcome messages. Update votes go to the director as product feedback.

TABLE — community_content_votes (supabase-sql/community-content-votes.sql)
targetType: update | review | leader_message | announcement

UI — ContentVoteButtons.tsx + useCommunityContentVotes.ts
Used in UpdatesList, CommunityReviews, StaffMessage, DirectorMessage

Cannot vote on your own review. Sign in required.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_gofundme-footer-improvements',
  '2026-06-09',
  'GoFundMe footer improvements',
  'Removed from the map tab. Tap the footer elsewhere for the full breakdown.',
  $detail$WHAT NEIGHBORS SEE
GoFundMe strip removed from under the map. On other scrollable pages it sits at the bottom; tap for full cost breakdown.

COMPONENTS — GoFundMeFooter.tsx, PageScrollFooter.tsx, GoFundMeSupport.tsx
PUBLIC PAGE — src/components/public/pages/GoFundMePage.tsx

SIGNED-IN — tap footer opens full-screen GoFundMe panel from App.tsx

COPY — src/siteContent.ts GOFUNDME constants$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_push-notifications',
  '2026-06-09',
  'Push notifications',
  'Optional alerts for messages, claims, and community activity. Turn them on or off in your account settings.',
  $detail$WHAT NEIGHBORS SEE
Optional browser push for messages, claims, new listings, comments, and more — controlled per account in settings.

TABLES — push_subscriptions, notification_preferences (supabase-sql/push-notifications.sql, notifications-complete.sql)

CLIENT — src/lib/pushNotifications.ts, usePushNotifications.ts, NotificationSettings.tsx
SERVER — api/push/* routes, server/push.ts, public/service-worker.js

Enable in Account → Push notifications. iPhone: Add to Home Screen for background delivery.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_gofundme-on-its-own-page',
  '2026-06-09',
  'GoFundMe on its own page',
  'Full cost breakdown lives on a dedicated page. Every other screen has a short support link at the bottom.',
  $detail$WHAT NEIGHBORS SEE
Full hosting cost breakdown on a dedicated page; every other screen shows a short optional support link at the bottom.

ROUTE — #/gofundme via src/public/routes.ts
PAGE — GoFundMePage.tsx renders GoFundMeSupport.tsx

Explains Vercel, Supabase, domain, and why the app stays free with no ads.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_updates-reviews-pages',
  '2026-06-09',
  'Updates & Reviews pages',
  'Changelog and neighbor reviews — both in the menu under Community.',
  $detail$WHAT NEIGHBORS SEE
Public Updates and Reviews pages for guests and neighbors — changelog oldest→newest, star reviews, director note.

ROUTES — #/updates, #/reviews in src/public/routes.ts
PAGES — UpdatesPage.tsx, ReviewsPage.tsx (public shell PublicSite.tsx)

IN-APP — Community hub tiles mirror same data via UpdatesList and CommunityReviews

Update votes feed back to director.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_cleaner-feed-filters',
  '2026-06-09',
  'Cleaner feed filters',
  'Filters and sorting now live in one “Filters & sort” panel so the feed stays easy to scroll.',
  $detail$WHAT NEIGHBORS SEE
Filters and sorting moved into one “Filters & sort” panel so the Stuff feed stays easy to scroll.

UI — src/components/ItemGrid.tsx
Single panel: type (give/look), category, neighborhood, status, vote/comment filters, sort order

Mobile-friendly sheet instead of many inline controls.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_smarter-quick-picks',
  '2026-06-09',
  'Smarter quick picks',
  'Tap multiple quick filters at once — Trending, Saved, My area, With photos, and Needs pickup.',
  $detail$WHAT NEIGHBORS SEE
Tap multiple quick filters at once — Trending, Saved, My area, With photos, Needs pickup.

LOGIC — ItemGrid.tsx quickPicks state (multi-select)
Trending = recent activity; Saved = useSavedItems hook; My area = your neighborhood; etc.

Combines with full Filters & sort panel.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_more-ways-to-browse-the-feed',
  '2026-06-09',
  'More ways to browse the feed',
  'Filter by giving vs. looking for, category, neighborhood, status, votes, and comments. Sort by newest, oldest, or most active.',
  $detail$WHAT NEIGHBORS SEE
Filter by giving vs looking, category, neighborhood, status, votes, comments. Sort by newest, oldest, or most active.

ENGAGEMENT DATA — useItemsEngagement.ts loads item_votes + item_comments for filter predicates

UI — ItemGrid.tsx filter state persisted in component session

Helps find active ISO requests or popular giveaways quickly.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_withdrawn-posts-stay-hidden',
  '2026-06-09',
  'Withdrawn posts stay hidden',
  'If someone removes a listing, it no longer clutters the community feed.',
  $detail$WHAT NEIGHBORS SEE
When a neighbor withdraws a listing, it disappears from the community feed and map.

STATUS — items.status = 'withdrawn' (src/types.ts PostStatus)

QUERIES — getSupabaseItems filters active statuses for feed/map
Owner can still see withdrawn posts in profile history where applicable.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_free-community-events',
  '2026-06-09',
  'Free community events',
  'Post neighborhood gatherings, RSVP (going / maybe / can’t go), and leave comments. Every event must be 100% free.',
  $detail$WHAT NEIGHBORS SEE
Post free neighborhood gatherings, RSVP (going/maybe/can't go), comment on events. Paid/ticketed events are blocked.

TABLES — community_events, event_rsvps, event_comments (supabase-sql/all-community-updates.sql + supabase-setup.sql)
CHECK constraint isFree = true

UI — EventsView.tsx, EventCard.tsx, EventDetailView.tsx, PostEventModal.tsx
REALTIME — useEventsRealtime.ts, useEventsEngagement.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_a-note-from-your-director',
  '2026-06-09',
  'A note from your director',
  'Markeith White shares why the app exists — free forever, no ads, and your info is never sold.',
  $detail$WHAT NEIGHBORS SEE
Director welcome message on home and reviews — free forever, no ads, your data is not sold.

TABLE — director_message (id 'main')
DEFAULT COPY — src/siteContent.ts DIRECTOR_MESSAGE_DEFAULT

UI — DirectorMessage.tsx, LeadershipMessagesCarousel.tsx
HOOK — useDirectorMessage.ts with realtime sync

Director can edit from Community hub when signed in as director.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_star-reviews',
  '2026-06-09',
  'Star reviews',
  'Leave a quick rating for the app. One review per person, updated anytime.',
  $detail$WHAT NEIGHBORS SEE
Leave a 0.5–5 star rating and optional text. One review per neighbor; edit anytime.

TABLE — app_reviews (supabase-sql/all-community-updates.sql)
UNIQUE userId

UI — CommunityReviews.tsx (in-app), public ReviewsPage.tsx
VOTES — community_content_votes targetType 'review'$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-09_support-the-app-optional',
  '2026-06-09',
  'Support the app (optional)',
  'A GoFundMe link explains what it costs to run Sacramento Buy Nothing — and why we will never charge you or show ads.',
  $detail$WHAT NEIGHBORS SEE
Optional GoFundMe link explains real monthly costs — app stays 100% free, no ads, no selling data.

COPY — src/siteContent.ts GOFUNDME section
UI — GoFundMeFooter.tsx, GoFundMeSupport.tsx, GoFundMePage.tsx

Never required to participate in the community.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-07_save-listings-labor-section',
  '2026-06-07',
  'Save listings & Labor section',
  'Bookmark posts to check later. New Labor section for community help and skills. Added Old Foothill Farms to the area list.',
  $detail$WHAT NEIGHBORS SEE
Bookmark listings to check later. New Labor categories for community help/skills. Added Old Foothill Farms to neighborhood list.

SAVED — useSavedItems.ts + saved_items sync (see saved-bookmarks update)

LABOR — src/types.ts categories: Labor & Services, Labor & Services Needed, Help / Labor Request
PostItemModal.tsx category picker; map pin colors in SacramentoMapView.tsx

NEIGHBORHOODS — SACRAMENTO_NEIGHBORHOODS in src/types.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-07_smoother-mobile-home-page',
  '2026-06-07',
  'Smoother mobile home page',
  'Fixed layout quirks on phones so browsing before you sign in feels better.',
  $detail$WHAT NEIGHBORS SEE
Guest home page layout fixed on phones — less horizontal scroll, better spacing before sign-in.

FILES — src/components/public/pages/HomePage.tsx, HomeScrollStage.tsx, public layout CSS in src/index.css

Touch-friendly sections and stats bar alignment on narrow screens.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-02_preview-listings-before-joining',
  '2026-06-02',
  'Preview listings before joining',
  'Guests can browse real community posts on the home page without signing in first.',
  $detail$WHAT NEIGHBORS SEE
Guests browse real active listings on the public home page without creating an account first.

COMPONENT — GuestListingPreview.tsx
Read-only cards; tap opens GuestItemDetailView.tsx with sign-in CTA to message

DATA — App.tsx passes visibleItems subset to PublicSite$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-02_animated-public-home-page',
  '2026-06-02',
  'Animated public home page',
  'Scroll-driven motion on the welcome page so the site feels alive before you sign in.',
  $detail$WHAT NEIGHBORS SEE
Scroll-driven motion on the welcome page — depth layers move at different speeds as you scroll.

COMPONENT — HomeScrollStage.tsx
Used by HomePage.tsx for pre-login marketing experience

Respects reduced-motion where possible via CSS.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-02_tap-photos-to-enlarge',
  '2026-06-02',
  'Tap photos to enlarge',
  'Listing images open in a lightbox so you can see details before you message someone.',
  $detail$WHAT NEIGHBORS SEE
Tap listing photos to open a full-screen lightbox before messaging the giver.

COMPONENTS — ImageLightbox.tsx, ListingPhotoGallery.tsx
Used in ItemDetailView.tsx and listing cards

Escape or backdrop tap closes overlay.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-02_delete-your-account',
  '2026-06-02',
  'Delete your account',
  'You can remove your account and data when you no longer want to participate.',
  $detail$WHAT NEIGHBORS SEE
Remove your account and community data when you no longer want to participate.

UI — UserProfileView.tsx delete section
SERVER — deleteOwnAccount() in src/supabase.ts

SQL — supabase-sql/account-deletion.sql (delete_own_account RPC + cascades)

Staff can also delete accounts from StaffModerationPanel.tsx (higher permission).$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-06-02_staff-safety-tools',
  '2026-06-02',
  'Staff safety tools',
  'Leaders can remove comments, delete accounts, and fully purge data when needed.',
  $detail$WHAT NEIGHBORS SEE (STAFF)
Leaders can remove comments, suspend/ban neighbors, delete accounts, and purge data when safety requires it.

PANEL — StaffModerationPanel.tsx
ROLES — src/lib/roles.ts canStaffSuspend, canStaffBan, canStaffDeleteAccount

AUDIT — moderation_audit_log table tracks actions
API — src/supabase.ts staff moderation helpers$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-31_clearer-claim-hold-buttons',
  '2026-05-31',
  'Clearer claim & hold buttons',
  'Easier to see when something is available, on hold, or already claimed.',
  $detail$WHAT NEIGHBORS SEE
Clearer buttons and labels for available, on hold, pending pickup, and claimed states on listings and in chat.

UI — ItemDetailView.tsx status actions, ChatSystem.tsx hold/pending pickup buttons
STATUSES — active | on_hold | pending_pickup | completed | withdrawn

ChatClaimActions.tsx for giveaway claim confirm flow.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_help-support-tab',
  '2026-05-29',
  'Help & support tab',
  'Report problems, open support tickets, and reach staff from one dedicated place in the app.',
  $detail$WHAT NEIGHBORS SEE
Dedicated Community hub tab for reports, app updates, announcements, and reviews (support tickets now under Chat).

UI — AccountHelpSection.tsx in CommunityMenuView.tsx
TAB — app tab 'menu' labeled Community (src/siteContent.ts)

Staff moderation panel on same tab for staff roles.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_support-tickets-with-photos',
  '2026-05-29',
  'Support tickets with photos',
  'Attach pictures when you report an issue so staff can help faster.',
  $detail$WHAT NEIGHBORS SEE
Attach a photo when opening a support ticket so staff can see what you see.

UI — ChatSupportSection.tsx (Chat tab), SupportTicketThread.tsx
STORAGE — upload to Supabase storage; support_ticket_messages.imageUrl column

API — createSupportTicket, addSupportTicketMessage in src/supabase.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_pick-up-several-items-at-once',
  '2026-05-29',
  'Pick up several items at once',
  'Claim multiple listings in one trip when a neighbor is giving away more than one thing.',
  $detail$WHAT NEIGHBORS SEE
Multi-item giveaways: claim specific subitems or several things in one trip.

TABLES — listing_subitems, item_claims, item_claim_requests
UI — SubItemPicker.tsx, ClaimAtPickupButton.tsx, ChatClaimActions.tsx

MESSAGES — formatSelfClaimRequestMessage in src/lib/claims.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_block-report',
  '2026-05-29',
  'Block & report',
  'Block someone who makes you uncomfortable and report serious issues to staff.',
  $detail$WHAT NEIGHBORS SEE
Block a neighbor (hide their posts/chats) or send a one-way report to staff.

BLOCK — BlockNeighborModal.tsx, user_blocks table, useBlockedUsers.ts
REPORT — ReportNeighborModal.tsx, user_reports table, AccountHelpSection report form

Blocked neighbors cannot DM you; chats hidden via filterChatsByBlocked in src/supabase.ts.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_staff-moderation-tools',
  '2026-05-29',
  'Staff moderation tools',
  'Community leaders can review reports, manage accounts, and keep the space safe.',
  $detail$WHAT NEIGHBORS SEE (STAFF)
Review reports, manage support tickets, view directory, suspend/ban, audit log.

PANEL — StaffModerationPanel.tsx
PERMS — src/lib/roles.ts staff rank system

TABLES — user_reports, support_tickets, moderation_audit_log$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_team-directory',
  '2026-05-29',
  'Team directory',
  'See who helps run the community and what role they play.',
  $detail$WHAT NEIGHBORS SEE
See who helps run Sacramento Buy Nothing and their role (moderator, administrator, city manager, director).

UI — staff directory section in StaffModerationPanel.tsx
BADGES — RoleBadge.tsx + roleLabel() from src/lib/roles.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_neighbor-profiles-avatars',
  '2026-05-29',
  'Neighbor profiles & avatars',
  'View profiles from the directory and see neighbor photos at a glance.',
  $detail$WHAT NEIGHBORS SEE
Tap avatars to open neighbor profiles with photo, neighborhood, bio, and listings.

UI — NeighborProfileView.tsx
Linked from ItemCard, ChatSystem, map pins, comments

Avatars from Google sign-in photoURL or dicebear fallback.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_message-requests',
  '2026-05-29',
  'Message requests',
  'New chats start as a request so you can accept or decline before talking.',
  $detail$WHAT NEIGHBORS SEE
Cold DMs from profiles start as a request — accept or decline before chatting. Listing messages skip the gate.

TABLE — message_requests (status pending|accepted|declined)
UI — ChatSystem incoming requests section, NeighborProfileView send/accept

API — sendMessageRequest, acceptMessageRequest in src/supabase.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_38-sacramento-neighborhoods',
  '2026-05-29',
  '38 Sacramento neighborhoods',
  'Pick your area from a fuller list that covers more of the region.',
  $detail$WHAT NEIGHBORS SEE
Pick from 38 Sacramento-area neighborhoods when joining or posting — better local matching.

CONST — SACRAMENTO_NEIGHBORHOODS in src/types.ts
MAP — NEIGHBORHOOD_COORDS for pin placement
PUBLIC — NeighborhoodsPage.tsx lists all areas$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_steadier-sign-in-listings',
  '2026-05-29',
  'Steadier sign-in & listings',
  'Stay signed in after refreshing, and posts load reliably once you are logged in.',
  $detail$WHAT NEIGHBORS SEE
Stay signed in after refresh; listings load reliably once logged in.

AUTH — Supabase auth session in App.tsx
CACHE — readCachedProfile/readCachedItems for faster first paint
FIXES — profile + items fetch retries in src/supabase.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_pinned-mobile-header-nav',
  '2026-05-29',
  'Pinned mobile header & nav',
  'The top bar and bottom tabs stay put while you scroll so the app feels stable on phones.',
  $detail$WHAT NEIGHBORS SEE
Top header and bottom tab bar stay fixed while scrolling on phones.

CSS — sbn-mobile-shell, sbn-mobile-header, bottom nav in MobileView.tsx
safe-area insets for notched iPhones$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_live-updates-everywhere',
  '2026-05-29',
  'Live updates everywhere',
  'New posts, chats, votes, and ticket replies appear without refreshing the page.',
  $detail$WHAT NEIGHBORS SEE
New posts, chat messages, votes, ticket replies, and events appear without manual refresh.

HELPER — src/lib/supabaseRealtime.ts subscribePostgresChanges()
USED BY — useItemsRealtime, ChatSystem, useEventsEngagement, usePushNotifications, etc.

Supabase Realtime publication on public tables (supabase-setup.sql).$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_faster-photos',
  '2026-05-29',
  'Faster photos',
  'Images load quicker and upload more smoothly when you post listings.',
  $detail$WHAT NEIGHBORS SEE
Listing photos load faster and upload more smoothly when posting.

CLIENT — src/lib/imageUrl.ts compressImageIfNeeded before upload
STORAGE — Supabase storage buckets for listing images

ListingImage component with lazy-friendly loading.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_listing-detail-page',
  '2026-05-29',
  'Listing detail page',
  'Tap any post for the full story — photos, comments, interest votes, and claim options.',
  $detail$WHAT NEIGHBORS SEE
Tap any post for full photos, description, comments, votes, bookmark, and claim/message actions.

UI — ItemDetailView.tsx + ListingEngagement.tsx
Opened from ItemGrid, map popups, profile listings$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_share-pickup-location-in-chat',
  '2026-05-29',
  'Share pickup location in chat',
  'Send your porch or meetup spot privately when arranging a pickup.',
  $detail$WHAT NEIGHBORS SEE
Listing owner can send porch/meetup address privately in the coordination chat.

BUTTON — ChatSystem.tsx “Send pickup location”
FORMAT — formatPickupLocationMessage() in src/lib/itemLocation.ts
Respects showExactLocation privacy flag on items.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_real-driving-routes-on-the-map',
  '2026-05-29',
  'Real driving routes on the map',
  'Directions to free gifts use real streets instead of straight lines.',
  $detail$WHAT NEIGHBORS SEE
Directions to free gifts use real streets (OSRM) instead of straight lines.

MODULE — src/lib/mapRoute.ts fetchRoute(), openDrivingDirections()
MAP — SacramentoMapView.tsx draws polyline overlay

Falls back to Haversine line if routing API unavailable.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_edit-your-own-posts',
  '2026-05-29',
  'Edit your own posts',
  'Update a listing anytime if details change before it is claimed.',
  $detail$WHAT NEIGHBORS SEE
Edit your listing title, description, photos, and category before it is claimed.

UI — PostItemModal.tsx in edit mode from ItemDetailView
API — updateSupabaseItem in src/supabase.ts

Saved-item bookmarkers can get push on owner edits (if enabled).$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_community-stats-bar',
  '2026-05-29',
  'Community stats bar',
  'See live counts of neighbors, posts, and gifts at the top of the feed.',
  $detail$WHAT NEIGHBORS SEE
Live counts of neighbors, active posts, items given, and requests fulfilled at top of Stuff feed.

COMPONENT — CommunityStatsBar.tsx
DATA — getCommunityStats() in src/supabase.ts aggregates users/items/claims$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_community-stats-on-public-home',
  '2026-05-29',
  'Community stats on public home',
  'The welcome page shows how active the community is before you join.',
  $detail$WHAT NEIGHBORS SEE
Welcome page shows community activity before you join — same stats as in-app bar.

HomePage.tsx embeds CommunityStatsBar (compact variant)
Builds trust for new visitors.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_role-badges',
  '2026-05-29',
  'Role badges',
  'Director and staff roles show on profiles so you know who helps run things.',
  $detail$WHAT NEIGHBORS SEE
Director and staff roles show on profiles and messages so you know who helps run the app.

COMPONENT — RoleBadge.tsx
LABELS — ROLE_LABELS in src/lib/roles.ts (city_moderator, city_administrator, city_manager, director)$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_director-role-management',
  '2026-05-29',
  'Director role management',
  'The director can assign staff roles from neighbor profiles.',
  $detail$WHAT NEIGHBORS SEE (DIRECTOR)
Director assigns staff roles from neighbor profiles — neighbor → moderator → administrator → manager → director.

UI — role picker on NeighborProfileView / staff tools
API — updateUserRole in src/supabase.ts

Legacy role slugs normalized in normalizeUserRole().$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_public-welcome-site',
  '2026-05-29',
  'Public welcome site',
  'About, How It Works, Rules, Areas, and Community pages for guests before they sign in.',
  $detail$WHAT NEIGHBORS SEE
Public pages before sign-in: Home, About, How It Works, Rules, Areas, Community, Updates, Reviews, GoFundMe.

ROUTER — src/components/public/PublicSite.tsx hash routes (#/home, etc.)
CONFIG — src/public/routes.ts

App.tsx shows PublicSite until userProfile exists.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_fresh-design-system',
  '2026-05-29',
  'Fresh design system',
  'Modern cards, cleaner navigation, better dark/light themes, and a more polished look throughout.',
  $detail$WHAT NEIGHBORS SEE
Modern cards, cleaner navigation, light/dark themes, consistent buttons and inputs across the app.

CSS — src/index.css design tokens (--color-accent, sbn-btn, sbn-card, item-feed-card)
ThemeToggle.tsx persists preference

Mobile/tablet/desktop shells share the same visual language.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_map-opens-first',
  '2026-05-29',
  'Map opens first',
  'The neighborhood map is the default tab so you see gifts near you right away.',
  $detail$WHAT NEIGHBORS SEE
Default tab after sign-in is the neighborhood map so you see gifts near you immediately.

DEFAULT TAB — App.tsx initial tab 'map' (localStorage sbn_active_tab_v1)

SacramentoMapView.tsx with category-colored pins.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_post-from-the-feed',
  '2026-05-29',
  'Post from the feed',
  'A Post button on the feed view on every screen size — not just the map.',
  $detail$WHAT NEIGHBORS SEE
Post button on Stuff feed and events — create giveaway or ISO from any screen size.

FAB / header buttons in MobileView, DesktopView
PostItemModal.tsx, PostEventModal.tsx$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_full-screen-mobile-chat-profile',
  '2026-05-29',
  'Full-screen mobile chat & profile',
  'Chat and account pages use the full phone screen, matching map and feed.',
  $detail$WHAT NEIGHBORS SEE
Chat and Account tabs use the full phone screen like Map and Stuff — no cramped nested boxes.

LAYOUT — MobileView.tsx tab panes with min-h-0 flex columns
ChatSystem fullBleed mode$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_tab-history-back-button',
  '2026-05-29',
  'Tab history & back button',
  'Your phone back button moves between tabs the way you expect.',
  $detail$WHAT NEIGHBORS SEE
Android back button and browser back move between app tabs as expected.

HISTORY — App.tsx TAB_HISTORY_KEY sbnTab in window.history state
parseTabFromHistoryState on popstate$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_iso-fulfillment-credits',
  '2026-05-29',
  'ISO fulfillment credits',
  'Neighbors who give generously earn credit when they ask for something they need.',
  $detail$WHAT NEIGHBORS SEE
When someone helps fulfill your ISO request, they get “items given” credit and you get “items claimed” credit.

FLOW — ChatSystem “Mark request fulfilled” → markItemFulfilledFromChat() in src/supabase.ts
CLAIM TYPE — request_fulfilled in item_claims

STATS — getNeighborStats() on NeighborProfileView / UserProfileView$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-29_map-color-index',
  '2026-05-29',
  'Map color index',
  'A quick legend on the map explains what each pin color means.',
  $detail$WHAT NEIGHBORS SEE
Legend on the map explains pin colors for giveaways, ISO requests, labor, pending pickup, etc.

UI — SacramentoMapView.tsx color guide toggle / index
Category → color mapping in map marker renderer$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-28_everything-saved-online',
  '2026-05-28',
  'Everything saved online',
  'All posts, profiles, and messages now live in the cloud so nothing is lost between devices.',
  $detail$WHAT NEIGHBORS SEE
Posts, profiles, chats, and votes live in Supabase — same community on every device, nothing stuck on one phone.

MIGRATION from early local-only prototypes to cloud-backed app
CORE — src/supabase.ts + supabase-setup.sql schema

Realtime sync across sessions.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_install-on-your-home-screen',
  '2026-05-20',
  'Install on your home screen',
  'Add Sacramento Buy Nothing to your phone like an app — works offline for basic browsing.',
  $detail$WHAT NEIGHBORS SEE
Install Sacramento Buy Nothing like an app — icon on home screen, standalone display mode, basic offline shell.

PWA — public/manifest.json, InstallPrompt.tsx, registerServiceWorker.ts
beforeinstallprompt handling on Android/desktop Chrome$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_neighbor-chat',
  '2026-05-20',
  'Neighbor chat',
  'Message the person giving something away to arrange porch pickup.',
  $detail$WHAT NEIGHBORS SEE
Message the person giving something away to arrange porch pickup.

TABLES — chats, messages (two-participant DMs, optional itemId context)
UI — ChatSystem.tsx

Start from listing Message button or accepted profile request.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_user-roles',
  '2026-05-20',
  'User roles',
  'Early staff and director roles so the community can be moderated as it grows.',
  $detail$WHAT NEIGHBORS SEE
Staff and director roles so the growing community can be moderated fairly.

ROLES — users.role column, src/lib/roles.ts
Early foundation for StaffModerationPanel and RoleBadge.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_interactive-sacramento-map',
  '2026-05-20',
  'Interactive Sacramento map',
  'Leaflet map with zoom controls, custom pins, and driving directions to free items.',
  $detail$WHAT NEIGHBORS SEE
Leaflet map with zoom, custom pins per listing type, and driving directions to items.

COMPONENT — SacramentoMapView.tsx (react-leaflet)
ROUTE — src/lib/mapRoute.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_photos-on-listings',
  '2026-05-19',
  'Photos on listings',
  'Upload pictures when you post so neighbors know exactly what you are giving away.',
  $detail$WHAT NEIGHBORS SEE
Upload photos when posting so neighbors know exactly what you are giving or seeking.

STORAGE — Supabase storage upload from PostItemModal.tsx
normalizeItemMedia in src/lib/listingContent.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_neighborhood-map-feed',
  '2026-05-19',
  'Neighborhood map & feed',
  'Browse free gifts on a map or in a scrollable feed — giving and looking for items.',
  $detail$WHAT NEIGHBORS SEE
Browse free gifts on a map or scrollable Stuff feed — giveaways (OFFER) and ISO requests.

TABS — map + feed (now Stuff) in app navigation
TYPES — PostType giveaway | looking in src/types.ts$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_sacramento-neighborhood-list',
  '2026-05-19',
  'Sacramento neighborhood list',
  'Pick your area when you join so posts stay local to your part of town.',
  $detail$WHAT NEIGHBORS SEE
Pick your neighborhood at onboarding so posts stay local to your part of Sacramento.

ONBOARDING — Onboarding.tsx neighborhood select
Used for feed filters, map centering, and profile display.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_works-on-phone-tablet-desktop',
  '2026-05-19',
  'Works on phone, tablet & desktop',
  'Layouts adapt to your screen — one community app wherever you open it.',
  $detail$WHAT NEIGHBORS SEE
Layouts adapt to screen size — MobileView, TabletView, DesktopView shells in App.tsx.

Responsive breakpoints at 768px and 1024px
One codebase, three layouts.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_offline-friendly',
  '2026-05-19',
  'Offline-friendly',
  'Basic browsing still works if your connection drops for a moment.',
  $detail$WHAT NEIGHBORS SEE
Basic browsing survives brief connection drops — cached profile/items and service worker shell.

readCachedProfile, readCachedItems in App.tsx initial state
Service worker caches static assets.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_orange-sage-branding',
  '2026-05-19',
  'Orange & sage branding',
  'Warm community colors and a local logo — built to feel like Sacramento, not a generic app.',
  $detail$WHAT NEIGHBORS SEE
Warm orange + sage community palette and Sacramento Buy Nothing logo — local feel, not a generic template.

ASSETS — public/Logo.jpeg, CSS variables in src/index.css
siteContent.ts SITE branding copy$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_sacramento-buy-nothing-launches',
  '2026-05-19',
  'Sacramento Buy Nothing launches',
  'The app goes live — a free place for Sacramento neighbors to give, ask, and connect with no money involved.',
  $detail$WHAT NEIGHBORS SEE
Sacramento Buy Nothing goes live — free local gifting, no selling, no bidding, neighbors helping neighbors.

VISION — src/siteContent.ts ABOUT, RULES, HOW_IT_WORKS
100% free rule enforced in post flows and moderation.

Launch date: May 19, 2026.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_hooked-up-to-a-real-database',
  '2026-05-20',
  'Hooked up to a real database',
  'Posts and accounts save online so neighbors see the same community on every visit.',
  $detail$WHAT NEIGHBORS SEE
Posts and accounts persist in Supabase — neighbors see the same listings every visit.

CLIENT — @supabase/supabase-js in src/supabase.ts
SCHEMA — supabase-setup.sql (users, items, chats, messages, …)

Replaced demo/local-only data store.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_full-screen-mobile-layout',
  '2026-05-20',
  'Full-screen mobile layout',
  'Map, feed, chat, and profile each use the whole phone screen — no cramped nested boxes.',
  $detail$WHAT NEIGHBORS SEE
Map, Stuff, Chat, and Profile each fill the phone — no double scroll containers.

Mobile shell refactor — sbn-mobile-shell CSS, flex min-h-0 children
Foundation for modern mobile UX.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-20_mobile-first-desktop-unchanged',
  '2026-05-20',
  'Mobile-first, desktop unchanged',
  'Reworked the phone experience while keeping the wider desktop layout neighbors already liked.',
  $detail$WHAT NEIGHBORS SEE
Phone experience rebuilt for touch-first use while desktop neighbors keep the wider layout they already used.

Parallel MobileView vs DesktopView components
Shared business logic in hooks + supabase.ts.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_the-community-vision',
  '2026-05-19',
  'The community vision',
  'Wrote down what Sacramento Buy Nothing is — free gifting, local neighbors, no selling, ever.',
  $detail$WHAT NEIGHBORS SEE
Written mission: free gifting, local neighbors, reduce waste, no money ever.

CONTENT — src/siteContent.ts SITE, ABOUT, RULES, principles array
Shown on public About and Rules pages.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
),
(
  '2026-05-19_where-it-all-started',
  '2026-05-19',
  'Where it all started',
  'First session: build a web app so Sacramento neighbors can give freely and ask kindly — May 19, 2026.',
  $detail$WHAT NEIGHBORS SEE
First build session — May 19, 2026 — web app for Sacramento neighbors to give freely and ask kindly.

Origin changelog entry documenting project start
Stack: React + Vite + Supabase + Vercel.$detail$,
  'Markeith White',
  'Buy Nothing Director',
  'director'
)

ON CONFLICT (id) DO UPDATE SET
  date = EXCLUDED.date,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  detail = EXCLUDED.detail,
  "updatedAt" = NOW();
