-- =========================================================
-- SERVER-SIDE PUSH WEBHOOKS — all director alert categories
-- =========================================================
--
-- Auth: Authorization: Bearer <SUPABASE_SERVICE_ROLE_KEY>
-- (Optional: use SUPABASE_PUSH_WEBHOOK_SECRET in Vercel instead.)
--
-- URL for every webhook:
--   https://sacramento-buy-nothing.vercel.app/api/webhooks/supabase-push
--
-- | Webhook name       | Table                     | Events | Director category   |
-- |--------------------|---------------------------|--------|---------------------|
-- | push-users-join    | users                     | INSERT | New neighbors       |
-- | push-users-leave   | users                     | DELETE | Account departures  |
-- | push-listings      | items                     | INSERT | New listings        |
-- | push-dm-requests   | message_requests          | INSERT | Message requests    |
-- | push-claim-reqs    | item_claim_requests       | INSERT | Claim requests      |
-- | push-moderation    | moderation_audit_log      | INSERT | Moderation actions  |
-- | push-reports       | user_reports              | INSERT | Neighbor reports    |
-- | push-support       | support_ticket_messages   | INSERT | Support tickets     |
--
-- Each category respects the matching toggle under Director oversight
-- in notification settings (directorJoins, directorLeaves, etc.).
