-- =========================================================
-- SERVER-SIDE PUSH WEBHOOKS — complete neighbor + staff list
-- =========================================================
--
-- Run supabase-sql/notifications-complete.sql FIRST.
--
-- Auth: Authorization: Bearer <SUPABASE_SERVICE_ROLE_KEY>
-- URL (all webhooks): https://sacramento-buy-nothing.vercel.app/api/webhooks/supabase-push
--
-- | Webhook name          | Table                   | Events         | Who gets notified                |
-- |-----------------------|-------------------------|----------------|----------------------------------|
-- | push-users-join       | users                   | INSERT         | Directors: new neighbors         |
-- | push-users-leave      | users                   | DELETE         | Directors: departures            |
-- | push-listings-insert  | items                   | INSERT         | Discover + directors             |
-- | push-listings-update  | items                   | UPDATE         | Owner status, saved-item alerts  |
-- | push-dm-requests      | message_requests        | INSERT, UPDATE | DM requests + directors          |
-- | push-claim-reqs       | item_claim_requests     | INSERT         | Giver + directors                |
-- | push-item-claims      | item_claims             | INSERT         | Listing owner (claim)            |
-- | push-comments         | item_comments           | INSERT         | Owner + saved-item bookmarkers   |
-- | push-votes            | item_votes              | INSERT, UPDATE | Listing owner (up/down)          |
-- | push-messages         | messages                | INSERT         | Chat participant                 |
-- | push-moderation       | moderation_audit_log    | INSERT         | Directors                        |
-- | push-reports          | user_reports            | INSERT         | Staff inbox                      |
-- | push-support          | support_ticket_messages | INSERT         | Support + staff inbox            |
--
-- items UPDATE covers: status changes, owner listing-status alerts, saved-item
-- status alerts, and saved-item alerts when the owner edits/saves their post.
--
-- Daily cron (Vercel): /api/cron/notification-jobs — listing expiry + pickup reminders.
