-- =========================================================
-- SERVER-SIDE PUSH WEBHOOK (recommended for director joins,
-- departures, support tickets, and reports)
-- =========================================================
--
-- Uses SUPABASE_SERVICE_ROLE_KEY you already have in Vercel.
-- Optional: set SUPABASE_PUSH_WEBHOOK_SECRET in Vercel and use
-- that instead of the service role in webhook headers.
--
-- In Supabase → Database → Webhooks → Create webhook for EACH row:
--
-- | Name              | Table                     | Events | URL |
-- |-------------------|---------------------------|--------|-----|
-- | push-users-join   | users                     | INSERT | https://sacramento-buy-nothing.vercel.app/api/webhooks/supabase-push |
-- | push-users-leave  | users                     | DELETE | https://sacramento-buy-nothing.vercel.app/api/webhooks/supabase-push |
-- | push-support      | support_ticket_messages   | INSERT | same URL |
-- | push-reports      | user_reports              | INSERT | same URL |
--
-- HTTP header (pick one):
--   Authorization: Bearer <your SUPABASE_SERVICE_ROLE_KEY>
--   OR Authorization: Bearer <SUPABASE_PUSH_WEBHOOK_SECRET>
--
-- Join/departure alerts use directorCategory join/leave so they
-- respect the "New neighbors" and "Account departures" toggles.
