-- Push webhooks (run in Supabase Dashboard → Database → Webhooks if not already configured)
-- URL: https://www.sacramentobuynothing.com/api/webhooks/supabase-push
-- Auth: Authorization: Bearer <SUPABASE_PUSH_WEBHOOK_SECRET>
--
-- | Webhook name                 | Table                       | Events         | Purpose                                      |
-- |------------------------------|-----------------------------|----------------|----------------------------------------------|
-- | push-feed-posts              | feed_posts                  | INSERT         | New feed post alerts                         |
-- | push-feed-comments           | feed_post_comments          | INSERT         | Feed comments + nested reply notifications   |
-- | push-feed-reactions          | feed_post_reactions         | INSERT         | Reaction notifications                       |
-- | push-feed-votes              | community_content_votes     | INSERT, UPDATE | Upvote/downvote (targetType=feed_post)       |
-- | push-friend-requests         | friend_requests             | INSERT, UPDATE | Friend request sent + accepted               |
-- | push-user-awards             | user_awards                 | INSERT         | Award unlocked                               |
-- | push-event-rsvps             | event_rsvps                 | INSERT, UPDATE | RSVP on a hosted event                       |
-- | push-event-comments          | event_comments              | INSERT         | Comments on hosted events + thread replies   |
-- | push-announcement-comments   | help_announcement_comments  | INSERT         | Comments on news posts you published/replied |
-- | push-update-comments         | app_update_comments         | INSERT         | Comments on updates you published/replied    |
